<?php
namespace Magenest\Chapter1\Model\ResourceModel\Rule;

/**
 * Image Collection
 */
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_eventPrefix     = 'catalog_category';
    /**
     * @var string
     */
    protected $_idFieldName = 'id';

    /**
     * Initialize resource collection
     * *
    @return void
     */
    public function _construct()
    {
        $this->_init('Magenest\Chapter1\Model\Rule', 'Magenest\Chapter1\Model\ResourceModel\Rule');
    }

    public function getItems()
    {
        $this->addFieldToFilter('status','pending');
        return parent::getItems(); // TODO: Change the autogenerated stub
    }
}
